### ISSUE TITLE
#1

### ISSUE THREAD

**Issue by dchernovolenko** [JackieW001/turbo-dollop#1]
1) Interactivity? What kind will you have? Anything except toggles?
2) How will you combine the sources?
3) Not very clear on how interaction will work. Doesn't seem to encourage much.
4) Otherwise clear on the aim.
5) Maybe more data, such as racial breakdowns of each state as well

**Comment by DimitriyL** [comment]
1. We may also include clickability within the data points, allowing a viewer to view data about the state, restaurant, etc. We could also have variable size for each data point based on either urbanization or income.
2. Links are available to excel spreadsheets provided by the census.gov links. We are still in the process of determining which specific years to use.
3. Toggling at the very least.
5. We will attempt to find such statistics at earliest possible convenience.
